[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self' https://images.unsplash.com; img-src 'self' data: https://images.unsplash.com;"
